### ISSUE TITLE
how to use on r110?

### ISSUE THREAD

**Issue by xsdxy** [c3nb/Overlayer#13]
I am a Chinese player and I found there is a bug.Maybe these pictures will help you to solve the problems
![image](https://github.com/c3nb/Overlayer/assets/112529420/114b918c-cc13-4191-94af-fded74c68dbe)
<img width="1920" alt="Snipaste_2023-06-09_09-42-17" src="https://github.com/c3nb/Overlayer/assets/112529420/7115f55a-d4c3-472e-b1ae-426b3ef28361">

**Comment by c3nb** [comment]
oh.. i'll fix that soon..
i didn't know chinese characters are invisible..
sorry for your user experience.

**Comment by xsdxy** [comment]
Thank you for solving the problem.Your mod is very useful in adofai and many Chinese players use it in their games,so I think it will widely used.And I think the way I use the mod is also wrong because I use a Chinese kanji ”丨” instead of “:”,maybe that is why it can’t display.But if you will fix it,it will be better.Thank you again for making this mod.

***@***.***

 

发件人: ***@***.*** ***@***.***> 代表 C#Newbie
发送时间: 2023年6月9日星期五 上午 09:50
收件人: c3nb/Overlayer ***@***.***>
抄送: xsdxy ***@***.***>; Author ***@***.***>
主题: Re: [c3nb/Overlayer] how to use on r110? (Issue #13)

 

oh.. i'll fix that soon..
i didn't know chinese characters are invisible..
sorry for your user experience.

**Comment by xsdxy** [comment]
https://1drv.ms/v/s!Ak7NBMl6fdX753lTCdkKs7gwaTM0

here is a video that can help you

 

***@***.***

 

发件人: ***@***.*** ***@***.***> 代表 C#Newbie
发送时间: 2023年6月9日星期五 上午 09:50
收件人: c3nb/Overlayer ***@***.***>
抄送: xsdxy ***@***.***>; Author ***@***.***>
主题: Re: [c3nb/Overlayer] how to use on r110? (Issue #13)

 

oh.. i'll fix that soon..
i didn't know chinese characters are invisible..
sorry for your user experience.
