### ISSUE TITLE
怎么用 How to use

### ISSUE THREAD

**Issue by gglyr** [c3nb/Overlayer#2]
怎么用 How to use

**Comment by punishzhang** [comment]
可以在这个网页直接下载文件吗？请问你是如何下载的? Can we download the mod file directly form this web page? how can you download?

**Comment by punishzhang** [comment]
你是点击什么按钮下载的呢？你下载的是否是源码？源码下载后是无法当作Mod使用的。你需要在正式版的位置下载，但是这里没有正式版 Which button you pressed to download? have you downloaded the original code? Original code can not be used as a mod file, you need to download it in "releases" but it is nothing in the "release" web page.

**Comment by punishzhang** [comment]
如果你成功下载并且能够兼容新版本（r89+)地打开游戏并不会出现bug ，进入游戏后打开关上再打开模组，如果还显示为可用，请告诉我或者分享一下你的文件，谢谢。如果是技术上的问题，你可以点击配置页面底下的"Tags" 来查看所有可以显示的指令。 If you have download this mod and not conflict to r89+, no bug when entering game, please open mod and close it then open again, if it still useful, please send the file to me, thank you. If technological problems, click the "Tags" button to see all commands you can use.
